Lê os dados:

In [61]:
import pandas as pd
df = pd.read_csv("Base_Dissertacaov10.csv",sep=';',decimal=",",encoding = "latin")
# print(df.head())

In [62]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#Cria os dados
y = df["AUTO"].to_numpy()
X = df.iloc[:,3:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12345)

#Padroniza os dados
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Random Over Sampler

In [63]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=12345)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')


 Accuracy Score: 0.9943872778297475
 Precision Score: [0.99438728 0.        ]
 Recall Score: [1. 0.]


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Over Sampler
Copiado de : https://audreymychan.com/unbalancedclasses.html

In [65]:
# Method to rebalance train data, model a logistic regression, and output charts for predictions on test data
# Inputs: X data, y data, rebalance algorithm (i.e. SMOTE()), rebalancing_title as a str (i.e. 'SMOTE')
from imblearn.metrics import classification_report_imbalanced, sensitivity_specificity_support,sensitivity_score,specificity_score,geometric_mean_score, make_index_balanced_accuracy
def rebalance_train_test_logreg(X, y, rebalance_alg, rebalancing_title, test_size=0.1):

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 12345)
    scaler = preprocessing.StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Rebalance train data
    rebalance = rebalance_alg
    X_reb, y_reb = rebalance.fit_sample(X_train, y_train)

    # Train a Logistic Regression model on resampled data
    logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
    logreg.fit(X_reb, y_reb)

    # Generate predictions
    y_pred = logreg.predict(X_test)

    # Print out metrics
    print(f'-------------------------------{rebalancing_title} test size={test_size}--------------------------------------')
    print("----------   Standard Metrics   -------------------")
    print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
    print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')
    print("----------   Imbalanced Metrics   -------------------")
    print(f' Classification report imbalanced: {classification_report_imbalanced(y_test, y_pred)}')
    print(f' Sensitivity specificity support:')
    print(sensitivity_specificity_support(y_test, y_pred))
    print(f' Sensitivity score: {sensitivity_score(y_test, y_pred)}')
    print(f' Specificity score: {specificity_score(y_test, y_pred)}')
    print(f' Geometric mean score: {geometric_mean_score(y_test, y_pred)}')

    return None


# ClusterCentroids

In [66]:
test_size=0.1
try:
    from imblearn.under_sampling import ClusterCentroids
    rebalance_train_test_logreg(X, y, ClusterCentroids(), 'ClusterCentroids',test_size)
except:
    print("Erro!")


-------------------------------ClusterCentroids test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8200810726535703
 Precision Score: [0.99771341 0.02058319]
 Recall Score: [0.82094701 0.66666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.82      0.67      0.90      0.74      0.56      3189
          1       0.02      0.67      0.82      0.04      0.74      0.54        18

avg / total       0.99      0.82      0.67      0.90      0.74      0.56      3207

 Sensitivity specificity support:
(array([0.82094701, 0.66666667]), array([0.66666667, 0.82094701]), array([3189,   18]))
 Sensitivity score: 0.6666666666666666
 Specificity score: 0.8209470053308248
 Geometric mean score: 0.7397959202062979


# CondensedNearestNeighbour

In [67]:
try:
    from imblearn.under_sampling import CondensedNearestNeighbour
    rebalance_train_test_logreg(X, y, CondensedNearestNeighbour(), 'CondensedNearestNeighbour',test_size)
except:
    print("Erro!")


-------------------------------CondensedNearestNeighbour test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.993140006236358
 Precision Score: [0.99438027 0.        ]
 Recall Score: [0.99874569 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      3189
          1       0.00      0.00      1.00      0.00      0.00      0.00        18

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      3207

 Sensitivity specificity support:
(array([0.99874569, 0.        ]), array([0.        , 0.99874569]), array([3189,   18]))
 Sensitivity score: 0.0
 Specificity score: 0.9987456883035434
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [68]:
try:
    from imblearn.under_sampling import EditedNearestNeighbours
    rebalance_train_test_logreg(X, y, EditedNearestNeighbours(), 'EditedNearestNeighbours',test_size)
except:
    print("Erro!")

-------------------------------EditedNearestNeighbours test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9934518241347053
 Precision Score: [0.99469082 0.2       ]
 Recall Score: [0.99874569 0.05555556]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.06      1.00      0.24      0.06      3189
          1       0.20      0.06      1.00      0.09      0.24      0.05        18

avg / total       0.99      0.99      0.06      0.99      0.24      0.06      3207

 Sensitivity specificity support:
(array([0.99874569, 0.05555556]), array([0.05555556, 0.99874569]), array([3189,   18]))
 Sensitivity score: 0.05555555555555555
 Specificity score: 0.9987456883035434
 Geometric mean score: 0.23555439196164238


# EditedNearestNeighbours

In [69]:
try:
    from imblearn.under_sampling import RepeatedEditedNearestNeighbours
    rebalance_train_test_logreg(X, y, RepeatedEditedNearestNeighbours(), 'RepeatedEditedNearestNeighbours',test_size)
except:
    print("Erro!")


-------------------------------RepeatedEditedNearestNeighbours test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9934518241347053
 Precision Score: [0.99469082 0.2       ]
 Recall Score: [0.99874569 0.05555556]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.06      1.00      0.24      0.06      3189
          1       0.20      0.06      1.00      0.09      0.24      0.05        18

avg / total       0.99      0.99      0.06      0.99      0.24      0.06      3207

 Sensitivity specificity support:
(array([0.99874569, 0.05555556]), array([0.05555556, 0.99874569]), array([3189,   18]))
 Sensitivity score: 0.05555555555555555
 Specificity score: 0.9987456883035434
 Geometric mean score: 0.23555439196164238


# AllKNN

In [70]:
try:
    from imblearn.under_sampling import AllKNN
    rebalance_train_test_logreg(X, y, AllKNN(), 'AllKNN',test_size)
except:
    print("Erro!")

-------------------------------AllKNN test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9934518241347053
 Precision Score: [0.99469082 0.2       ]
 Recall Score: [0.99874569 0.05555556]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.06      1.00      0.24      0.06      3189
          1       0.20      0.06      1.00      0.09      0.24      0.05        18

avg / total       0.99      0.99      0.06      0.99      0.24      0.06      3207

 Sensitivity specificity support:
(array([0.99874569, 0.05555556]), array([0.05555556, 0.99874569]), array([3189,   18]))
 Sensitivity score: 0.05555555555555555
 Specificity score: 0.9987456883035434
 Geometric mean score: 0.23555439196164238


# InstanceHardnessThreshold

In [71]:
try:
    from imblearn.under_sampling import InstanceHardnessThreshold
    rebalance_train_test_logreg(X, y, InstanceHardnessThreshold(), 'InstanceHardnessThreshold',test_size)
except:
    print("Erro!")


-------------------------------InstanceHardnessThreshold test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9912690988462738
 Precision Score: [0.99498904 0.14285714]
 Recall Score: [0.99623706 0.11111111]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.11      1.00      0.33      0.12      3189
          1       0.14      0.11      1.00      0.12      0.33      0.10        18

avg / total       0.99      0.99      0.12      0.99      0.33      0.12      3207

 Sensitivity specificity support:
(array([0.99623706, 0.11111111]), array([0.11111111, 0.99623706]), array([3189,   18]))
 Sensitivity score: 0.1111111111111111
 Specificity score: 0.9962370649106302
 Geometric mean score: 0.3327055863857597


# NearMiss

In [72]:
try:
    from imblearn.under_sampling import NearMiss
    rebalance_train_test_logreg(X, y, NearMiss(), 'NearMiss',test_size)
except:
    print("Erro!")

-------------------------------NearMiss test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.0894917368256938
 Precision Score: [0.97192982 0.00342231]
 Recall Score: [0.08686108 0.55555556]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.97      0.09      0.56      0.16      0.22      0.05      3189
          1       0.00      0.56      0.09      0.01      0.22      0.05        18

avg / total       0.97      0.09      0.55      0.16      0.22      0.05      3207

 Sensitivity specificity support:
(array([0.08686108, 0.55555556]), array([0.55555556, 0.08686108]), array([3189,   18]))
 Sensitivity score: 0.5555555555555556
 Specificity score: 0.08686108497961743
 Geometric mean score: 0.2196728438428603


# NeighbourhoodCleaningRule

In [73]:
try:
    from imblearn.under_sampling import NeighbourhoodCleaningRule
    rebalance_train_test_logreg(X, y, NeighbourhoodCleaningRule(), 'NeighbourhoodCleaningRule',test_size)
except:
    print("Erro!")

-------------------------------NeighbourhoodCleaningRule test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9934518241347053
 Precision Score: [0.99469082 0.2       ]
 Recall Score: [0.99874569 0.05555556]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.06      1.00      0.24      0.06      3189
          1       0.20      0.06      1.00      0.09      0.24      0.05        18

avg / total       0.99      0.99      0.06      0.99      0.24      0.06      3207

 Sensitivity specificity support:
(array([0.99874569, 0.05555556]), array([0.05555556, 0.99874569]), array([3189,   18]))
 Sensitivity score: 0.05555555555555555
 Specificity score: 0.9987456883035434
 Geometric mean score: 0.23555439196164238


# OneSidedSelection

In [74]:
try:
    from imblearn.under_sampling import OneSidedSelection
    rebalance_train_test_logreg(X, y, OneSidedSelection(), 'OneSidedSelection',test_size)
except:
    print("Erro!")

-------------------------------OneSidedSelection test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9943872778297475
 Precision Score: [0.99438728 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      3189
          1       0.00      0.00      1.00      0.00      0.00      0.00        18

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      3207

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([3189,   18]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RandomUnderSampler

In [75]:
try:
    from imblearn.under_sampling import RandomUnderSampler
    rebalance_train_test_logreg(X, y, RandomUnderSampler(), 'RandomUnderSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomUnderSampler test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.7477393202369816
 Precision Score: [0.99790795 0.01591187]
 Recall Score: [0.74788335 0.72222222]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.75      0.72      0.85      0.73      0.54      3189
          1       0.02      0.72      0.75      0.03      0.73      0.54        18

avg / total       0.99      0.75      0.72      0.85      0.73      0.54      3207

 Sensitivity specificity support:
(array([0.74788335, 0.72222222]), array([0.72222222, 0.74788335]), array([3189,   18]))
 Sensitivity score: 0.7222222222222222
 Specificity score: 0.7478833490122295
 Geometric mean score: 0.734940796450034


# TomekLinks

In [76]:
try:
    from imblearn.under_sampling import TomekLinks
    rebalance_train_test_logreg(X, y, TomekLinks(), 'TomekLinks',test_size)
except:
    print("Erro!")

-------------------------------TomekLinks test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9943872778297475
 Precision Score: [0.99438728 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      3189
          1       0.00      0.00      1.00      0.00      0.00      0.00        18

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      3207

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([3189,   18]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ADASYN

In [77]:
try:
    from imblearn.over_sampling import ADASYN
    rebalance_train_test_logreg(X, y, ADASYN(), 'ADASYN',test_size)
except:
    print("Erro!")

-------------------------------ADASYN test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8528219519800436
 Precision Score: [0.99780139 0.0251046 ]
 Recall Score: [0.85387269 0.66666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.85      0.67      0.92      0.75      0.58      3189
          1       0.03      0.67      0.85      0.05      0.75      0.56        18

avg / total       0.99      0.85      0.67      0.92      0.75      0.58      3207

 Sensitivity specificity support:
(array([0.85387269, 0.66666667]), array([0.66666667, 0.85387269]), array([3189,   18]))
 Sensitivity score: 0.6666666666666666
 Specificity score: 0.8538726873628096
 Geometric mean score: 0.7544855586701928


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BorderlineSMOTE

In [78]:
try:
    from imblearn.over_sampling import BorderlineSMOTE
    rebalance_train_test_logreg(X, y, BorderlineSMOTE(), 'BorderlineSMOTE',test_size)
except:
    print("Erro!")

-------------------------------BorderlineSMOTE test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9236046149048955
 Precision Score: [0.99662618 0.03292181]
 Recall Score: [0.92630919 0.44444444]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.93      0.44      0.96      0.64      0.43      3189
          1       0.03      0.44      0.93      0.06      0.64      0.39        18

avg / total       0.99      0.92      0.45      0.96      0.64      0.43      3207

 Sensitivity specificity support:
(array([0.92630919, 0.44444444]), array([0.44444444, 0.92630919]), array([3189,   18]))
 Sensitivity score: 0.4444444444444444
 Specificity score: 0.9263091878331765
 Geometric mean score: 0.6416330511829177


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# KMeansSMOTE

In [79]:
try:
    from imblearn.over_sampling import KMeansSMOTE
    rebalance_train_test_logreg(X, y, KMeansSMOTE(), 'KMeansSMOTE',test_size)
except:
    print("Erro!")

Erro!


# RandomOverSampler

In [80]:
try:
    from imblearn.over_sampling import RandomOverSampler
    rebalance_train_test_logreg(X, y, RandomOverSampler(), 'RandomOverSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomOverSampler test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8531337698783911
 Precision Score: [0.99816716 0.02713987]
 Recall Score: [0.85387269 0.72222222]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.85      0.72      0.92      0.79      0.62      3189
          1       0.03      0.72      0.85      0.05      0.79      0.61        18

avg / total       0.99      0.85      0.72      0.92      0.79      0.62      3207

 Sensitivity specificity support:
(array([0.85387269, 0.72222222]), array([0.72222222, 0.85387269]), array([3189,   18]))
 Sensitivity score: 0.7222222222222222
 Specificity score: 0.8538726873628096
 Geometric mean score: 0.7852934672859753


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTE

In [81]:
try:
    from imblearn.over_sampling import SMOTE
    rebalance_train_test_logreg(X, y, SMOTE(), 'SMOTE',test_size)
except:
    print("Erro!")

-------------------------------SMOTE test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8618646710321173
 Precision Score: [0.99782451 0.02672606]
 Recall Score: [0.86296645 0.66666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.67      0.93      0.76      0.59      3189
          1       0.03      0.67      0.86      0.05      0.76      0.56        18

avg / total       0.99      0.86      0.67      0.92      0.76      0.59      3207

 Sensitivity specificity support:
(array([0.86296645, 0.66666667]), array([0.66666667, 0.86296645]), array([3189,   18]))
 Sensitivity score: 0.6666666666666666
 Specificity score: 0.8629664471621198
 Geometric mean score: 0.7584925607906424


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTENC

In [82]:
try:
    from imblearn.over_sampling import SMOTENC
    rebalance_train_test_logreg(X, y, SMOTENC(), 'SMOTENC',test_size)
except:
    print("Erro!")

Erro!


# SVMSMOTE

In [83]:
try:
    from imblearn.over_sampling import SVMSMOTE
    rebalance_train_test_logreg(X, y, SVMSMOTE(), 'SVMSMOTE',test_size)
except:
    print("Erro!")

-------------------------------SVMSMOTE test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.943560960399127
 Precision Score: [0.99571523 0.02890173]
 Recall Score: [0.94731891 0.27777778]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.95      0.28      0.97      0.51      0.28      3189
          1       0.03      0.28      0.95      0.05      0.51      0.25        18

avg / total       0.99      0.94      0.28      0.97      0.51      0.28      3207

 Sensitivity specificity support:
(array([0.94731891, 0.27777778]), array([0.27777778, 0.94731891]), array([3189,   18]))
 Sensitivity score: 0.2777777777777778
 Specificity score: 0.9473189087488241
 Geometric mean score: 0.5129757706940141


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTEENN

In [84]:
try:
    from imblearn.combine import SMOTEENN
    rebalance_train_test_logreg(X, y, SMOTEENN(), 'SMOTEENN',test_size)
except:
    print("Erro!")

-------------------------------SMOTEENN test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8606173994387278
 Precision Score: [0.99782135 0.02649007]
 Recall Score: [0.86171214 0.66666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.67      0.92      0.76      0.59      3189
          1       0.03      0.67      0.86      0.05      0.76      0.56        18

avg / total       0.99      0.86      0.67      0.92      0.76      0.59      3207

 Sensitivity specificity support:
(array([0.86171214, 0.66666667]), array([0.66666667, 0.86171214]), array([3189,   18]))
 Sensitivity score: 0.6666666666666666
 Specificity score: 0.8617121354656632
 Geometric mean score: 0.7579411302846077


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTETomek

In [85]:
try:
    from imblearn.combine import SMOTETomek
    rebalance_train_test_logreg(X, y, SMOTETomek(), 'SMOTETomek',test_size)
except:
    print("Erro!")


-------------------------------SMOTETomek test size=0.2--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.862488306828812
 Precision Score: [0.99782609 0.02684564]
 Recall Score: [0.8635936  0.66666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.67      0.93      0.76      0.59      3189
          1       0.03      0.67      0.86      0.05      0.76      0.56        18

avg / total       0.99      0.86      0.67      0.92      0.76      0.59      3207

 Sensitivity specificity support:
(array([0.8635936 , 0.66666667]), array([0.66666667, 0.8635936 ]), array([3189,   18]))
 Sensitivity score: 0.6666666666666666
 Specificity score: 0.863593603010348
 Geometric mean score: 0.7587681257627823


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BalancedBaggingClassifier

In [86]:
try:
    from imblearn.ensemble import BalancedBaggingClassifier
    rebalance_train_test_logreg(X, y, BalancedBaggingClassifier(), 'BalancedBaggingClassifier',test_size)
except:
    print("Erro!")

Erro!


# BalancedRandomForestClassifier

In [87]:
try:
    from imblearn.ensemble import BalancedRandomForestClassifier
    rebalance_train_test_logreg(X, y, BalancedRandomForestClassifier(), 'BalancedRandomForestClassifier',test_size)
except:
    print("Erro!")

Erro!


# EasyEnsemble

In [88]:
try:
    from imblearn.ensemble import EasyEnsembleClassifier
    rebalance_train_test_logreg(X, y, EasyEnsembleClassifier(), 'EasyEnsembleClassifier',test_size)
except:
    print("Erro!")

Erro!


# RUSBoostClassifier

In [89]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!


# RUSBoostClassifier

In [90]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!
