Lê os dados:

In [1]:
import pandas as pd
df = pd.read_csv("Base_Dissertacaov10.csv",sep=';',decimal=",",encoding = "latin")
# print(df.head())

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#Cria os dados
y = df["AUTO"].to_numpy()
X = df.iloc[:,3:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 12345)

#Padroniza os dados
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Random Over Sampler

In [3]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=12345)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')


 Accuracy Score: 0.9956345494231369
 Precision Score: [0.99563455 0.        ]
 Recall Score: [1. 0.]


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Over Sampler
Copiado de : https://audreymychan.com/unbalancedclasses.html

In [5]:
# Method to rebalance train data, model a logistic regression, and output charts for predictions on test data
# Inputs: X data, y data, rebalance algorithm (i.e. SMOTE()), rebalancing_title as a str (i.e. 'SMOTE')
from imblearn.metrics import classification_report_imbalanced, sensitivity_specificity_support,sensitivity_score,specificity_score,geometric_mean_score, make_index_balanced_accuracy
def rebalance_train_test_logreg(X, y, rebalance_alg, rebalancing_title, test_size=0.2):

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 12345)
    scaler = preprocessing.StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Rebalance train data
    rebalance = rebalance_alg
    X_reb, y_reb = rebalance.fit_sample(X_train, y_train)

    # Train a Logistic Regression model on resampled data
    logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
    logreg.fit(X_reb, y_reb)

    # Generate predictions
    y_pred = logreg.predict(X_test)

    # Print out metrics
    print(f'-------------------------------{rebalancing_title} test size={test_size}--------------------------------------')
    print("----------   Standard Metrics   -------------------")
    print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
    print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')
    print("----------   Imbalanced Metrics   -------------------")
    print(f' Classification report imbalanced: {classification_report_imbalanced(y_test, y_pred)}')
    print(f' Sensitivity specificity support:')
    print(sensitivity_specificity_support(y_test, y_pred))
    print(f' Sensitivity score: {sensitivity_score(y_test, y_pred)}')
    print(f' Specificity score: {specificity_score(y_test, y_pred)}')
    print(f' Geometric mean score: {geometric_mean_score(y_test, y_pred)}')

    return None


# ClusterCentroids

In [6]:
test_size=0.4
try:
    from imblearn.under_sampling import ClusterCentroids
    rebalance_train_test_logreg(X, y, ClusterCentroids(), 'ClusterCentroids',test_size)
except:
    print("Erro!")


-------------------------------ClusterCentroids test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8029310882444652
 Precision Score: [0.99902572 0.01794072]
 Recall Score: [0.80284998 0.82142857]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.80      0.82      0.89      0.81      0.66      6386
          1       0.02      0.82      0.80      0.04      0.81      0.66        28

avg / total       0.99      0.80      0.82      0.89      0.81      0.66      6414

 Sensitivity specificity support:
(array([0.80284998, 0.82142857]), array([0.82142857, 0.80284998]), array([6386,   28]))
 Sensitivity score: 0.8214285714285714
 Specificity score: 0.8028499843407454
 Geometric mean score: 0.8120861504227673


# CondensedNearestNeighbour

In [7]:
try:
    from imblearn.under_sampling import CondensedNearestNeighbour
    rebalance_train_test_logreg(X, y, CondensedNearestNeighbour(), 'CondensedNearestNeighbour',test_size)
except:
    print("Erro!")


-------------------------------CondensedNearestNeighbour test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9934518241347053
 Precision Score: [0.99593496 0.11111111]
 Recall Score: [0.99749452 0.07142857]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.07      1.00      0.27      0.08      6386
          1       0.11      0.07      1.00      0.09      0.27      0.06        28

avg / total       0.99      0.99      0.08      0.99      0.27      0.08      6414

 Sensitivity specificity support:
(array([0.99749452, 0.07142857]), array([0.07142857, 0.99749452]), array([6386,   28]))
 Sensitivity score: 0.07142857142857142
 Specificity score: 0.9974945192608832
 Geometric mean score: 0.2669262229879906


# EditedNearestNeighbours

In [8]:
try:
    from imblearn.under_sampling import EditedNearestNeighbours
    rebalance_train_test_logreg(X, y, EditedNearestNeighbours(), 'EditedNearestNeighbours',test_size)
except:
    print("Erro!")

-------------------------------EditedNearestNeighbours test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9948550046772685
 Precision Score: [0.99563114 0.        ]
 Recall Score: [0.99921704 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([0.99921704, 0.        ]), array([0.        , 0.99921704]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 0.999217037269026
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [9]:
try:
    from imblearn.under_sampling import RepeatedEditedNearestNeighbours
    rebalance_train_test_logreg(X, y, RepeatedEditedNearestNeighbours(), 'RepeatedEditedNearestNeighbours',test_size)
except:
    print("Erro!")


-------------------------------RepeatedEditedNearestNeighbours test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9948550046772685
 Precision Score: [0.99563114 0.        ]
 Recall Score: [0.99921704 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([0.99921704, 0.        ]), array([0.        , 0.99921704]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 0.999217037269026
 Geometric mean score: 0.0


# AllKNN

In [10]:
try:
    from imblearn.under_sampling import AllKNN
    rebalance_train_test_logreg(X, y, AllKNN(), 'AllKNN',test_size)
except:
    print("Erro!")

-------------------------------AllKNN test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9948550046772685
 Precision Score: [0.99563114 0.        ]
 Recall Score: [0.99921704 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([0.99921704, 0.        ]), array([0.        , 0.99921704]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 0.999217037269026
 Geometric mean score: 0.0


# InstanceHardnessThreshold

In [11]:
try:
    from imblearn.under_sampling import InstanceHardnessThreshold
    rebalance_train_test_logreg(X, y, InstanceHardnessThreshold(), 'InstanceHardnessThreshold',test_size)
except:
    print("Erro!")


-------------------------------InstanceHardnessThreshold test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9914250077954475
 Precision Score: [0.99670485 0.17073171]
 Recall Score: [0.99467585 0.25      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.99      0.25      1.00      0.50      0.27      6386
          1       0.17      0.25      0.99      0.20      0.50      0.23        28

avg / total       0.99      0.99      0.25      0.99      0.50      0.27      6414

 Sensitivity specificity support:
(array([0.99467585, 0.25      ]), array([0.25      , 0.99467585]), array([6386,   28]))
 Sensitivity score: 0.25
 Specificity score: 0.9946758534293768
 Geometric mean score: 0.49866718696676265


# NearMiss

In [12]:
try:
    from imblearn.under_sampling import NearMiss
    rebalance_train_test_logreg(X, y, NearMiss(), 'NearMiss',test_size)
except:
    print("Erro!")

-------------------------------NearMiss test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.05472404115996258
 Precision Score: [0.98498498 0.00378227]
 Recall Score: [0.05136236 0.82142857]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.05      0.82      0.10      0.21      0.04      6386
          1       0.00      0.82      0.05      0.01      0.21      0.05        28

avg / total       0.98      0.05      0.82      0.10      0.21      0.04      6414

 Sensitivity specificity support:
(array([0.05136236, 0.82142857]), array([0.82142857, 0.05136236]), array([6386,   28]))
 Sensitivity score: 0.8214285714285714
 Specificity score: 0.05136235515189477
 Geometric mean score: 0.2054032765503702


# NeighbourhoodCleaningRule

In [13]:
try:
    from imblearn.under_sampling import NeighbourhoodCleaningRule
    rebalance_train_test_logreg(X, y, NeighbourhoodCleaningRule(), 'NeighbourhoodCleaningRule',test_size)
except:
    print("Erro!")

-------------------------------NeighbourhoodCleaningRule test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9951668225756158
 Precision Score: [0.99563251 0.        ]
 Recall Score: [0.99953022 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([0.99953022, 0.        ]), array([0.        , 0.99953022]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 0.9995302223614156
 Geometric mean score: 0.0


# OneSidedSelection

In [14]:
try:
    from imblearn.under_sampling import OneSidedSelection
    rebalance_train_test_logreg(X, y, OneSidedSelection(), 'OneSidedSelection',test_size)
except:
    print("Erro!")

-------------------------------OneSidedSelection test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9956345494231369
 Precision Score: [0.99563455 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RandomUnderSampler

In [15]:
try:
    from imblearn.under_sampling import RandomUnderSampler
    rebalance_train_test_logreg(X, y, RandomUnderSampler(), 'RandomUnderSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomUnderSampler test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.7860929217337075
 Precision Score: [0.99840954 0.01445087]
 Recall Score: [0.78640777 0.71428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.79      0.71      0.88      0.75      0.57      6386
          1       0.01      0.71      0.79      0.03      0.75      0.56        28

avg / total       0.99      0.79      0.71      0.88      0.75      0.57      6414

 Sensitivity specificity support:
(array([0.78640777, 0.71428571]), array([0.71428571, 0.78640777]), array([6386,   28]))
 Sensitivity score: 0.7142857142857143
 Specificity score: 0.7864077669902912
 Geometric mean score: 0.7494797085742173


# TomekLinks

In [16]:
try:
    from imblearn.under_sampling import TomekLinks
    rebalance_train_test_logreg(X, y, TomekLinks(), 'TomekLinks',test_size)
except:
    print("Erro!")

-------------------------------TomekLinks test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9956345494231369
 Precision Score: [0.99563455 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      6386
          1       0.00      0.00      1.00      0.00      0.00      0.00        28

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      6414

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([6386,   28]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ADASYN

In [17]:
try:
    from imblearn.over_sampling import ADASYN
    rebalance_train_test_logreg(X, y, ADASYN(), 'ADASYN',test_size)
except:
    print("Erro!")

-------------------------------ADASYN test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8565637667602121
 Precision Score: [0.99854068 0.02145923]
 Recall Score: [0.8571876  0.71428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.71      0.92      0.78      0.62      6386
          1       0.02      0.71      0.86      0.04      0.78      0.60        28

avg / total       0.99      0.86      0.71      0.92      0.78      0.62      6414

 Sensitivity specificity support:
(array([0.8571876 , 0.71428571]), array([0.71428571, 0.8571876 ]), array([6386,   28]))
 Sensitivity score: 0.7142857142857143
 Specificity score: 0.8571875978703414
 Geometric mean score: 0.7824812174242092


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BorderlineSMOTE

In [18]:
try:
    from imblearn.over_sampling import BorderlineSMOTE
    rebalance_train_test_logreg(X, y, BorderlineSMOTE(), 'BorderlineSMOTE',test_size)
except:
    print("Erro!")

-------------------------------BorderlineSMOTE test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9228250701590271
 Precision Score: [0.99763474 0.02828283]
 Recall Score: [0.92467899 0.5       ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.92      0.50      0.96      0.68      0.48      6386
          1       0.03      0.50      0.92      0.05      0.68      0.44        28

avg / total       0.99      0.92      0.50      0.96      0.68      0.48      6414

 Sensitivity specificity support:
(array([0.92467899, 0.5       ]), array([0.5       , 0.92467899]), array([6386,   28]))
 Sensitivity score: 0.5
 Specificity score: 0.9246789852803007
 Geometric mean score: 0.679955507838675


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# KMeansSMOTE

In [19]:
try:
    from imblearn.over_sampling import KMeansSMOTE
    rebalance_train_test_logreg(X, y, KMeansSMOTE(), 'KMeansSMOTE',test_size)
except:
    print("Erro!")

Erro!


# RandomOverSampler

In [20]:
try:
    from imblearn.over_sampling import RandomOverSampler
    rebalance_train_test_logreg(X, y, RandomOverSampler(), 'RandomOverSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomOverSampler test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8587464920486436
 Precision Score: [0.99836304 0.02074236]
 Recall Score: [0.85953649 0.67857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.68      0.92      0.76      0.59      6386
          1       0.02      0.68      0.86      0.04      0.76      0.57        28

avg / total       0.99      0.86      0.68      0.92      0.76      0.59      6414

 Sensitivity specificity support:
(array([0.85953649, 0.67857143]), array([0.67857143, 0.85953649]), array([6386,   28]))
 Sensitivity score: 0.6785714285714286
 Specificity score: 0.8595364860632634
 Geometric mean score: 0.7637125776476478


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTE

In [21]:
try:
    from imblearn.over_sampling import SMOTE
    rebalance_train_test_logreg(X, y, SMOTE(), 'SMOTE',test_size)
except:
    print("Erro!")

/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


-------------------------------SMOTE test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8620205799812909
 Precision Score: [0.99836927 0.02122905]
 Recall Score: [0.86282493 0.67857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.68      0.93      0.77      0.60      6386
          1       0.02      0.68      0.86      0.04      0.77      0.57        28

avg / total       0.99      0.86      0.68      0.92      0.77      0.60      6414

 Sensitivity specificity support:
(array([0.86282493, 0.67857143]), array([0.67857143, 0.86282493]), array([6386,   28]))
 Sensitivity score: 0.6785714285714286
 Specificity score: 0.8628249295333542
 Geometric mean score: 0.765172101582703


# SMOTENC

In [22]:
try:
    from imblearn.over_sampling import SMOTENC
    rebalance_train_test_logreg(X, y, SMOTENC(), 'SMOTENC',test_size)
except:
    print("Erro!")

Erro!


# SVMSMOTE

In [23]:
try:
    from imblearn.over_sampling import SVMSMOTE
    rebalance_train_test_logreg(X, y, SVMSMOTE(), 'SVMSMOTE',test_size)
except:
    print("Erro!")

-------------------------------SVMSMOTE test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9370127845338322
 Precision Score: [0.99750499 0.03233831]
 Recall Score: [0.9390855  0.46428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.94      0.46      0.97      0.66      0.46      6386
          1       0.03      0.46      0.94      0.06      0.66      0.42        28

avg / total       0.99      0.94      0.47      0.96      0.66      0.46      6414

 Sensitivity specificity support:
(array([0.9390855 , 0.46428571]), array([0.46428571, 0.9390855 ]), array([6386,   28]))
 Sensitivity score: 0.4642857142857143
 Specificity score: 0.9390854995302224
 Geometric mean score: 0.6603059759874554


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTEENN

In [24]:
try:
    from imblearn.combine import SMOTEENN
    rebalance_train_test_logreg(X, y, SMOTEENN(), 'SMOTEENN',test_size)
except:
    print("Erro!")

-------------------------------SMOTEENN test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8598378546928593
 Precision Score: [0.99836512 0.02090209]
 Recall Score: [0.86063263 0.67857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.68      0.92      0.76      0.59      6386
          1       0.02      0.68      0.86      0.04      0.76      0.57        28

avg / total       0.99      0.86      0.68      0.92      0.76      0.59      6414

 Sensitivity specificity support:
(array([0.86063263, 0.67857143]), array([0.67857143, 0.86063263]), array([6386,   28]))
 Sensitivity score: 0.6785714285714286
 Specificity score: 0.860632633886627
 Geometric mean score: 0.7641993953489101


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTETomek

In [25]:
try:
    from imblearn.combine import SMOTETomek
    rebalance_train_test_logreg(X, y, SMOTETomek(), 'SMOTETomek',test_size)
except:
    print("Erro!")


-------------------------------SMOTETomek test size=0.4--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8632678515746803
 Precision Score: [0.99837163 0.02142052]
 Recall Score: [0.86407767 0.67857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.68      0.93      0.77      0.60      6386
          1       0.02      0.68      0.86      0.04      0.77      0.58        28

avg / total       0.99      0.86      0.68      0.92      0.77      0.60      6414

 Sensitivity specificity support:
(array([0.86407767, 0.67857143]), array([0.67857143, 0.86407767]), array([6386,   28]))
 Sensitivity score: 0.6785714285714286
 Specificity score: 0.8640776699029126
 Geometric mean score: 0.7657273789428524


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BalancedBaggingClassifier

In [26]:
try:
    from imblearn.ensemble import BalancedBaggingClassifier
    rebalance_train_test_logreg(X, y, BalancedBaggingClassifier(), 'BalancedBaggingClassifier',test_size)
except:
    print("Erro!")

Erro!


# BalancedRandomForestClassifier

In [27]:
try:
    from imblearn.ensemble import BalancedRandomForestClassifier
    rebalance_train_test_logreg(X, y, BalancedRandomForestClassifier(), 'BalancedRandomForestClassifier',test_size)
except:
    print("Erro!")

Erro!


# EasyEnsemble

In [28]:
try:
    from imblearn.ensemble import EasyEnsembleClassifier
    rebalance_train_test_logreg(X, y, EasyEnsembleClassifier(), 'EasyEnsembleClassifier',test_size)
except:
    print("Erro!")

Erro!


# RUSBoostClassifier

In [29]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!


# RUSBoostClassifier

In [30]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!
