Lê os dados:

In [1]:
import pandas as pd
df = pd.read_csv("Base_Dissertacaov10.csv",sep=';',decimal=",",encoding = "latin")
# print(df.head())

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#Cria os dados
y = df["AUTO"].to_numpy()
X = df.iloc[:,3:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12345)

#Padroniza os dados
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Random Over Sampler

In [3]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=12345)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')


 Accuracy Score: 0.9943872778297475
 Precision Score: [0.99438728 0.        ]
 Recall Score: [1. 0.]


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Over Sampler
Copiado de : https://audreymychan.com/unbalancedclasses.html

In [5]:
# Method to rebalance train data, model a logistic regression, and output charts for predictions on test data
# Inputs: X data, y data, rebalance algorithm (i.e. SMOTE()), rebalancing_title as a str (i.e. 'SMOTE')
from imblearn.metrics import classification_report_imbalanced, sensitivity_specificity_support,sensitivity_score,specificity_score,geometric_mean_score, make_index_balanced_accuracy
def rebalance_train_test_logreg(X, y, rebalance_alg, rebalancing_title, test_size=0.1):

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 12345)
    scaler = preprocessing.StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Rebalance train data
    rebalance = rebalance_alg
    X_reb, y_reb = rebalance.fit_sample(X_train, y_train)

    # Train a Logistic Regression model on resampled data
    logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
    logreg.fit(X_reb, y_reb)

    # Generate predictions
    y_pred = logreg.predict(X_test)

    # Print out metrics
    print(f'-------------------------------{rebalancing_title} test size={test_size}--------------------------------------')
    print("----------   Standard Metrics   -------------------")
    print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
    print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')
    print("----------   Imbalanced Metrics   -------------------")
    print(f' Classification report imbalanced: {classification_report_imbalanced(y_test, y_pred)}')
    print(f' Sensitivity specificity support:')
    print(sensitivity_specificity_support(y_test, y_pred))
    print(f' Sensitivity score: {sensitivity_score(y_test, y_pred)}')
    print(f' Specificity score: {specificity_score(y_test, y_pred)}')
    print(f' Geometric mean score: {geometric_mean_score(y_test, y_pred)}')

    return None


# ClusterCentroids

In [6]:
test_size=0.1
try:
    from imblearn.under_sampling import ClusterCentroids
    rebalance_train_test_logreg(X, y, ClusterCentroids(), 'ClusterCentroids',test_size)
except:
    print("Erro!")


-------------------------------ClusterCentroids test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8185785536159601
 Precision Score: [0.99770467 0.03030303]
 Recall Score: [0.81909548 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.82      0.75      0.90      0.78      0.62      1592
          1       0.03      0.75      0.82      0.06      0.78      0.61        12

avg / total       0.99      0.82      0.75      0.89      0.78      0.62      1604

 Sensitivity specificity support:
(array([0.81909548, 0.75      ]), array([0.75      , 0.81909548]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8190954773869347
 Geometric mean score: 0.7837867108086236


# CondensedNearestNeighbour

In [7]:
try:
    from imblearn.under_sampling import CondensedNearestNeighbour
    rebalance_train_test_logreg(X, y, CondensedNearestNeighbour(), 'CondensedNearestNeighbour',test_size)
except:
    print("Erro!")


-------------------------------CondensedNearestNeighbour test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99251404 0.        ]
 Recall Score: [0.99937186 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      1592
          1       0.00      0.00      1.00      0.00      0.00      0.00        12

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      1604

 Sensitivity specificity support:
(array([0.99937186, 0.        ]), array([0.        , 0.99937186]), array([1592,   12]))
 Sensitivity score: 0.0
 Specificity score: 0.9993718592964824
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [8]:
try:
    from imblearn.under_sampling import EditedNearestNeighbours
    rebalance_train_test_logreg(X, y, EditedNearestNeighbours(), 'EditedNearestNeighbours',test_size)
except:
    print("Erro!")

-------------------------------EditedNearestNeighbours test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99251404 0.        ]
 Recall Score: [0.99937186 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      1592
          1       0.00      0.00      1.00      0.00      0.00      0.00        12

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      1604

 Sensitivity specificity support:
(array([0.99937186, 0.        ]), array([0.        , 0.99937186]), array([1592,   12]))
 Sensitivity score: 0.0
 Specificity score: 0.9993718592964824
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [9]:
try:
    from imblearn.under_sampling import RepeatedEditedNearestNeighbours
    rebalance_train_test_logreg(X, y, RepeatedEditedNearestNeighbours(), 'RepeatedEditedNearestNeighbours',test_size)
except:
    print("Erro!")


-------------------------------RepeatedEditedNearestNeighbours test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99312929 0.33333333]
 Recall Score: [0.99874372 0.08333333]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.08      1.00      0.29      0.09      1592
          1       0.33      0.08      1.00      0.13      0.29      0.08        12

avg / total       0.99      0.99      0.09      0.99      0.29      0.09      1604

 Sensitivity specificity support:
(array([0.99874372, 0.08333333]), array([0.08333333, 0.99874372]), array([1592,   12]))
 Sensitivity score: 0.08333333333333333
 Specificity score: 0.9987437185929648
 Geometric mean score: 0.2884937490069419


# AllKNN

In [10]:
try:
    from imblearn.under_sampling import AllKNN
    rebalance_train_test_logreg(X, y, AllKNN(), 'AllKNN',test_size)
except:
    print("Erro!")

-------------------------------AllKNN test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99312929 0.33333333]
 Recall Score: [0.99874372 0.08333333]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.08      1.00      0.29      0.09      1592
          1       0.33      0.08      1.00      0.13      0.29      0.08        12

avg / total       0.99      0.99      0.09      0.99      0.29      0.09      1604

 Sensitivity specificity support:
(array([0.99874372, 0.08333333]), array([0.08333333, 0.99874372]), array([1592,   12]))
 Sensitivity score: 0.08333333333333333
 Specificity score: 0.9987437185929648
 Geometric mean score: 0.2884937490069419


# InstanceHardnessThreshold

In [11]:
try:
    from imblearn.under_sampling import InstanceHardnessThreshold
    rebalance_train_test_logreg(X, y, InstanceHardnessThreshold(), 'InstanceHardnessThreshold',test_size)
except:
    print("Erro!")


-------------------------------InstanceHardnessThreshold test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99374609 0.4       ]
 Recall Score: [0.99811558 0.16666667]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.17      1.00      0.41      0.18      1592
          1       0.40      0.17      1.00      0.24      0.41      0.15        12

avg / total       0.99      0.99      0.17      0.99      0.41      0.18      1604

 Sensitivity specificity support:
(array([0.99811558, 0.16666667]), array([0.16666667, 0.99811558]), array([1592,   12]))
 Sensitivity score: 0.16666666666666666
 Specificity score: 0.9981155778894473
 Geometric mean score: 0.40786345302675486


# NearMiss

In [12]:
try:
    from imblearn.under_sampling import NearMiss
    rebalance_train_test_logreg(X, y, NearMiss(), 'NearMiss',test_size)
except:
    print("Erro!")

-------------------------------NearMiss test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.08790523690773068
 Precision Score: [0.97777778 0.00612662]
 Recall Score: [0.08291457 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.08      0.75      0.15      0.25      0.06      1592
          1       0.01      0.75      0.08      0.01      0.25      0.07        12

avg / total       0.97      0.09      0.75      0.15      0.25      0.06      1604

 Sensitivity specificity support:
(array([0.08291457, 0.75      ]), array([0.75      , 0.08291457]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.0829145728643216
 Geometric mean score: 0.2493710681860292


# NeighbourhoodCleaningRule

In [13]:
try:
    from imblearn.under_sampling import NeighbourhoodCleaningRule
    rebalance_train_test_logreg(X, y, NeighbourhoodCleaningRule(), 'NeighbourhoodCleaningRule',test_size)
except:
    print("Erro!")

-------------------------------NeighbourhoodCleaningRule test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9918952618453866
 Precision Score: [0.99251404 0.        ]
 Recall Score: [0.99937186 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      1592
          1       0.00      0.00      1.00      0.00      0.00      0.00        12

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      1604

 Sensitivity specificity support:
(array([0.99937186, 0.        ]), array([0.        , 0.99937186]), array([1592,   12]))
 Sensitivity score: 0.0
 Specificity score: 0.9993718592964824
 Geometric mean score: 0.0


# OneSidedSelection

In [14]:
try:
    from imblearn.under_sampling import OneSidedSelection
    rebalance_train_test_logreg(X, y, OneSidedSelection(), 'OneSidedSelection',test_size)
except:
    print("Erro!")

-------------------------------OneSidedSelection test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9925187032418953
 Precision Score: [0.9925187 0.       ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      1592
          1       0.00      0.00      1.00      0.00      0.00      0.00        12

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      1604

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([1592,   12]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RandomUnderSampler

In [15]:
try:
    from imblearn.under_sampling import RandomUnderSampler
    rebalance_train_test_logreg(X, y, RandomUnderSampler(), 'RandomUnderSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomUnderSampler test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8391521197007481
 Precision Score: [0.99850523 0.03759398]
 Recall Score: [0.83919598 0.83333333]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.84      0.83      0.91      0.84      0.70      1592
          1       0.04      0.83      0.84      0.07      0.84      0.70        12

avg / total       0.99      0.84      0.83      0.91      0.84      0.70      1604

 Sensitivity specificity support:
(array([0.83919598, 0.83333333]), array([0.83333333, 0.83919598]), array([1592,   12]))
 Sensitivity score: 0.8333333333333334
 Specificity score: 0.8391959798994975
 Geometric mean score: 0.8362595190786059


# TomekLinks

In [16]:
try:
    from imblearn.under_sampling import TomekLinks
    rebalance_train_test_logreg(X, y, TomekLinks(), 'TomekLinks',test_size)
except:
    print("Erro!")

-------------------------------TomekLinks test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9925187032418953
 Precision Score: [0.9925187 0.       ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.99      1.00      0.00      1.00      0.00      0.00      1592
          1       0.00      0.00      1.00      0.00      0.00      0.00        12

avg / total       0.99      0.99      0.01      0.99      0.00      0.00      1604

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([1592,   12]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ADASYN

In [17]:
try:
    from imblearn.over_sampling import ADASYN
    rebalance_train_test_logreg(X, y, ADASYN(), 'ADASYN',test_size)
except:
    print("Erro!")

-------------------------------ADASYN test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8653366583541147
 Precision Score: [0.99782923 0.04054054]
 Recall Score: [0.86620603 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.75      0.93      0.81      0.66      1592
          1       0.04      0.75      0.87      0.08      0.81      0.64        12

avg / total       0.99      0.87      0.75      0.92      0.81      0.66      1604

 Sensitivity specificity support:
(array([0.86620603, 0.75      ]), array([0.75      , 0.86620603]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8662060301507538
 Geometric mean score: 0.8060114903728516


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BorderlineSMOTE

In [18]:
try:
    from imblearn.over_sampling import BorderlineSMOTE
    rebalance_train_test_logreg(X, y, BorderlineSMOTE(), 'BorderlineSMOTE',test_size)
except:
    print("Erro!")

-------------------------------BorderlineSMOTE test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9270573566084788
 Precision Score: [0.996633   0.05882353]
 Recall Score: [0.92964824 0.58333333]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.93      0.58      0.96      0.74      0.56      1592
          1       0.06      0.58      0.93      0.11      0.74      0.52        12

avg / total       0.99      0.93      0.59      0.96      0.74      0.56      1604

 Sensitivity specificity support:
(array([0.92964824, 0.58333333]), array([0.58333333, 0.92964824]), array([1592,   12]))
 Sensitivity score: 0.5833333333333334
 Specificity score: 0.9296482412060302
 Geometric mean score: 0.7364066861253938


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# KMeansSMOTE

In [19]:
try:
    from imblearn.over_sampling import KMeansSMOTE
    rebalance_train_test_logreg(X, y, KMeansSMOTE(), 'KMeansSMOTE',test_size)
except:
    print("Erro!")

Erro!


# RandomOverSampler

In [20]:
try:
    from imblearn.over_sampling import RandomOverSampler
    rebalance_train_test_logreg(X, y, RandomOverSampler(), 'RandomOverSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomOverSampler test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8591022443890274
 Precision Score: [0.99781341 0.0387931 ]
 Recall Score: [0.85992462 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.75      0.92      0.80      0.65      1592
          1       0.04      0.75      0.86      0.07      0.80      0.64        12

avg / total       0.99      0.86      0.75      0.92      0.80      0.65      1604

 Sensitivity specificity support:
(array([0.85992462, 0.75      ]), array([0.75      , 0.85992462]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8599246231155779
 Geometric mean score: 0.8030837237403604


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTE

In [21]:
try:
    from imblearn.over_sampling import SMOTE
    rebalance_train_test_logreg(X, y, SMOTE(), 'SMOTE',test_size)
except:
    print("Erro!")

-------------------------------SMOTE test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8703241895261845
 Precision Score: [0.99784173 0.04205607]
 Recall Score: [0.87123116 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.75      0.93      0.81      0.66      1592
          1       0.04      0.75      0.87      0.08      0.81      0.65        12

avg / total       0.99      0.87      0.75      0.92      0.81      0.66      1604

 Sensitivity specificity support:
(array([0.87123116, 0.75      ]), array([0.75      , 0.87123116]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8712311557788944
 Geometric mean score: 0.8083460687318093


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTENC

In [22]:
try:
    from imblearn.over_sampling import SMOTENC
    rebalance_train_test_logreg(X, y, SMOTENC(), 'SMOTENC',test_size)
except:
    print("Erro!")

Erro!


# SVMSMOTE

In [23]:
try:
    from imblearn.over_sampling import SVMSMOTE
    rebalance_train_test_logreg(X, y, SVMSMOTE(), 'SVMSMOTE',test_size)
except:
    print("Erro!")

-------------------------------SVMSMOTE test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.933291770573566
 Precision Score: [0.99665552 0.06422018]
 Recall Score: [0.93592965 0.58333333]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.94      0.58      0.97      0.74      0.57      1592
          1       0.06      0.58      0.94      0.12      0.74      0.53        12

avg / total       0.99      0.93      0.59      0.96      0.74      0.56      1604

 Sensitivity specificity support:
(array([0.93592965, 0.58333333]), array([0.58333333, 0.93592965]), array([1592,   12]))
 Sensitivity score: 0.5833333333333334
 Specificity score: 0.9359296482412061
 Geometric mean score: 0.738890358222407


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTEENN

In [24]:
try:
    from imblearn.combine import SMOTEENN
    rebalance_train_test_logreg(X, y, SMOTEENN(), 'SMOTEENN',test_size)
except:
    print("Erro!")

-------------------------------SMOTEENN test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8653366583541147
 Precision Score: [0.99782923 0.04054054]
 Recall Score: [0.86620603 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.75      0.93      0.81      0.66      1592
          1       0.04      0.75      0.87      0.08      0.81      0.64        12

avg / total       0.99      0.87      0.75      0.92      0.81      0.66      1604

 Sensitivity specificity support:
(array([0.86620603, 0.75      ]), array([0.75      , 0.86620603]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8662060301507538
 Geometric mean score: 0.8060114903728516


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTETomek

In [25]:
try:
    from imblearn.combine import SMOTETomek
    rebalance_train_test_logreg(X, y, SMOTETomek(), 'SMOTETomek',test_size)
except:
    print("Erro!")


-------------------------------SMOTETomek test size=0.1--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8678304239401496
 Precision Score: [0.9978355 0.0412844]
 Recall Score: [0.86871859 0.75      ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.75      0.93      0.81      0.66      1592
          1       0.04      0.75      0.87      0.08      0.81      0.64        12

avg / total       0.99      0.87      0.75      0.92      0.81      0.66      1604

 Sensitivity specificity support:
(array([0.86871859, 0.75      ]), array([0.75      , 0.86871859]), array([1592,   12]))
 Sensitivity score: 0.75
 Specificity score: 0.8687185929648241
 Geometric mean score: 0.8071796235805374


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BalancedBaggingClassifier

In [26]:
try:
    from imblearn.ensemble import BalancedBaggingClassifier
    rebalance_train_test_logreg(X, y, BalancedBaggingClassifier(), 'BalancedBaggingClassifier',test_size)
except:
    print("Erro!")

Erro!


# BalancedRandomForestClassifier

In [27]:
try:
    from imblearn.ensemble import BalancedRandomForestClassifier
    rebalance_train_test_logreg(X, y, BalancedRandomForestClassifier(), 'BalancedRandomForestClassifier',test_size)
except:
    print("Erro!")

Erro!


# EasyEnsemble

In [28]:
try:
    from imblearn.ensemble import EasyEnsembleClassifier
    rebalance_train_test_logreg(X, y, EasyEnsembleClassifier(), 'EasyEnsembleClassifier',test_size)
except:
    print("Erro!")

Erro!


# RUSBoostClassifier

In [29]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!


# RUSBoostClassifier

In [30]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!
