Lê os dados:

In [1]:
import pandas as pd
df = pd.read_csv("Base_Dissertacaov10.csv",sep=';',decimal=",",encoding = "latin")
# print(df.head())

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#Cria os dados
y = df["AUTO"].to_numpy()
X = df.iloc[:,3:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 12345)

#Padroniza os dados
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Random Over Sampler

In [3]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=12345)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')


 Accuracy Score: 0.9952192891290792
 Precision Score: [0.99521929 0.        ]
 Recall Score: [1. 0.]


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Over Sampler
Copiado de : https://audreymychan.com/unbalancedclasses.html

In [5]:
# Method to rebalance train data, model a logistic regression, and output charts for predictions on test data
# Inputs: X data, y data, rebalance algorithm (i.e. SMOTE()), rebalancing_title as a str (i.e. 'SMOTE')
from imblearn.metrics import classification_report_imbalanced, sensitivity_specificity_support,sensitivity_score,specificity_score,geometric_mean_score, make_index_balanced_accuracy
def rebalance_train_test_logreg(X, y, rebalance_alg, rebalancing_title, test_size=0.2):

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 12345)
    scaler = preprocessing.StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Rebalance train data
    rebalance = rebalance_alg
    X_reb, y_reb = rebalance.fit_sample(X_train, y_train)

    # Train a Logistic Regression model on resampled data
    logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
    logreg.fit(X_reb, y_reb)

    # Generate predictions
    y_pred = logreg.predict(X_test)

    # Print out metrics
    print(f'-------------------------------{rebalancing_title} test size={test_size}--------------------------------------')
    print("----------   Standard Metrics   -------------------")
    print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
    print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')
    print("----------   Imbalanced Metrics   -------------------")
    print(f' Classification report imbalanced: {classification_report_imbalanced(y_test, y_pred)}')
    print(f' Sensitivity specificity support:')
    print(sensitivity_specificity_support(y_test, y_pred))
    print(f' Sensitivity score: {sensitivity_score(y_test, y_pred)}')
    print(f' Specificity score: {specificity_score(y_test, y_pred)}')
    print(f' Geometric mean score: {geometric_mean_score(y_test, y_pred)}')

    return None


# ClusterCentroids

In [6]:
test_size=0.3
try:
    from imblearn.under_sampling import ClusterCentroids
    rebalance_train_test_logreg(X, y, ClusterCentroids(), 'ClusterCentroids',test_size)
except:
    print("Erro!")


-------------------------------ClusterCentroids test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8216586988152151
 Precision Score: [0.99847793 0.01956272]
 Recall Score: [0.82205514 0.73913043]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.82      0.74      0.90      0.78      0.61      4788
          1       0.02      0.74      0.82      0.04      0.78      0.60        23

avg / total       0.99      0.82      0.74      0.90      0.78      0.61      4811

 Sensitivity specificity support:
(array([0.82205514, 0.73913043]), array([0.73913043, 0.82205514]), array([4788,   23]))
 Sensitivity score: 0.7391304347826086
 Specificity score: 0.8220551378446115
 Geometric mean score: 0.7794908411587432


# CondensedNearestNeighbour

In [7]:
try:
    from imblearn.under_sampling import CondensedNearestNeighbour
    rebalance_train_test_logreg(X, y, CondensedNearestNeighbour(), 'CondensedNearestNeighbour',test_size)
except:
    print("Erro!")


-------------------------------CondensedNearestNeighbour test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9931407191852005
 Precision Score: [0.99520933 0.        ]
 Recall Score: [0.99791145 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      4788
          1       0.00      0.00      1.00      0.00      0.00      0.00        23

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      4811

 Sensitivity specificity support:
(array([0.99791145, 0.        ]), array([0.        , 0.99791145]), array([4788,   23]))
 Sensitivity score: 0.0
 Specificity score: 0.9979114452798663
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [8]:
try:
    from imblearn.under_sampling import EditedNearestNeighbours
    rebalance_train_test_logreg(X, y, EditedNearestNeighbours(), 'EditedNearestNeighbours',test_size)
except:
    print("Erro!")

-------------------------------EditedNearestNeighbours test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9948035751403035
 Precision Score: [0.9952173 0.       ]
 Recall Score: [0.99958229 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      4788
          1       0.00      0.00      1.00      0.00      0.00      0.00        23

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      4811

 Sensitivity specificity support:
(array([0.99958229, 0.        ]), array([0.        , 0.99958229]), array([4788,   23]))
 Sensitivity score: 0.0
 Specificity score: 0.9995822890559732
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [9]:
try:
    from imblearn.under_sampling import RepeatedEditedNearestNeighbours
    rebalance_train_test_logreg(X, y, RepeatedEditedNearestNeighbours(), 'RepeatedEditedNearestNeighbours',test_size)
except:
    print("Erro!")


-------------------------------RepeatedEditedNearestNeighbours test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9950114321346913
 Precision Score: [0.9958368  0.42857143]
 Recall Score: [0.99916458 0.13043478]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.13      1.00      0.36      0.14      4788
          1       0.43      0.13      1.00      0.20      0.36      0.12        23

avg / total       0.99      1.00      0.13      0.99      0.36      0.14      4811

 Sensitivity specificity support:
(array([0.99916458, 0.13043478]), array([0.13043478, 0.99916458]), array([4788,   23]))
 Sensitivity score: 0.13043478260869565
 Specificity score: 0.9991645781119465
 Geometric mean score: 0.361006668271295


# AllKNN

In [10]:
try:
    from imblearn.under_sampling import AllKNN
    rebalance_train_test_logreg(X, y, AllKNN(), 'AllKNN',test_size)
except:
    print("Erro!")

-------------------------------AllKNN test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9950114321346913
 Precision Score: [0.9958368  0.42857143]
 Recall Score: [0.99916458 0.13043478]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.13      1.00      0.36      0.14      4788
          1       0.43      0.13      1.00      0.20      0.36      0.12        23

avg / total       0.99      1.00      0.13      0.99      0.36      0.14      4811

 Sensitivity specificity support:
(array([0.99916458, 0.13043478]), array([0.13043478, 0.99916458]), array([4788,   23]))
 Sensitivity score: 0.13043478260869565
 Specificity score: 0.9991645781119465
 Geometric mean score: 0.361006668271295


# InstanceHardnessThreshold

In [11]:
try:
    from imblearn.under_sampling import InstanceHardnessThreshold
    rebalance_train_test_logreg(X, y, InstanceHardnessThreshold(), 'InstanceHardnessThreshold',test_size)
except:
    print("Erro!")


-------------------------------InstanceHardnessThreshold test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9931407191852005
 Precision Score: [0.99603589 0.22222222]
 Recall Score: [0.99707602 0.17391304]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.17      1.00      0.42      0.19      4788
          1       0.22      0.17      1.00      0.20      0.42      0.16        23

avg / total       0.99      0.99      0.18      0.99      0.42      0.19      4811

 Sensitivity specificity support:
(array([0.99707602, 0.17391304]), array([0.17391304, 0.99707602]), array([4788,   23]))
 Sensitivity score: 0.17391304347826086
 Specificity score: 0.9970760233918129
 Geometric mean score: 0.41641869051145125


# NearMiss

In [12]:
try:
    from imblearn.under_sampling import NearMiss
    rebalance_train_test_logreg(X, y, NearMiss(), 'NearMiss',test_size)
except:
    print("Erro!")

-------------------------------NearMiss test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.0856370816877988
 Precision Score: [0.98263027 0.00362976]
 Recall Score: [0.08270677 0.69565217]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.08      0.70      0.15      0.24      0.05      4788
          1       0.00      0.70      0.08      0.01      0.24      0.06        23

avg / total       0.98      0.09      0.69      0.15      0.24      0.05      4811

 Sensitivity specificity support:
(array([0.08270677, 0.69565217]), array([0.69565217, 0.08270677]), array([4788,   23]))
 Sensitivity score: 0.6956521739130435
 Specificity score: 0.08270676691729323
 Geometric mean score: 0.23986484153233964


# NeighbourhoodCleaningRule

In [13]:
try:
    from imblearn.under_sampling import NeighbourhoodCleaningRule
    rebalance_train_test_logreg(X, y, NeighbourhoodCleaningRule(), 'NeighbourhoodCleaningRule',test_size)
except:
    print("Erro!")

-------------------------------NeighbourhoodCleaningRule test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9945957181459156
 Precision Score: [0.99521631 0.        ]
 Recall Score: [0.99937343 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      4788
          1       0.00      0.00      1.00      0.00      0.00      0.00        23

avg / total       0.99      0.99      0.00      0.99      0.00      0.00      4811

 Sensitivity specificity support:
(array([0.99937343, 0.        ]), array([0.        , 0.99937343]), array([4788,   23]))
 Sensitivity score: 0.0
 Specificity score: 0.9993734335839599
 Geometric mean score: 0.0


# OneSidedSelection

In [14]:
try:
    from imblearn.under_sampling import OneSidedSelection
    rebalance_train_test_logreg(X, y, OneSidedSelection(), 'OneSidedSelection',test_size)
except:
    print("Erro!")

-------------------------------OneSidedSelection test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9952192891290792
 Precision Score: [0.99521929 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      4788
          1       0.00      0.00      1.00      0.00      0.00      0.00        23

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      4811

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([4788,   23]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RandomUnderSampler

In [15]:
try:
    from imblearn.under_sampling import RandomUnderSampler
    rebalance_train_test_logreg(X, y, RandomUnderSampler(), 'RandomUnderSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomUnderSampler test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.7424651839534401
 Precision Score: [0.99859511 0.014377  ]
 Recall Score: [0.74227235 0.7826087 ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.74      0.78      0.85      0.76      0.58      4788
          1       0.01      0.78      0.74      0.03      0.76      0.58        23

avg / total       0.99      0.74      0.78      0.85      0.76      0.58      4811

 Sensitivity specificity support:
(array([0.74227235, 0.7826087 ]), array([0.7826087 , 0.74227235]), array([4788,   23]))
 Sensitivity score: 0.782608695652174
 Specificity score: 0.7422723475355054
 Geometric mean score: 0.7621737293579719


# TomekLinks

In [16]:
try:
    from imblearn.under_sampling import TomekLinks
    rebalance_train_test_logreg(X, y, TomekLinks(), 'TomekLinks',test_size)
except:
    print("Erro!")

-------------------------------TomekLinks test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9952192891290792
 Precision Score: [0.99521929 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      4788
          1       0.00      0.00      1.00      0.00      0.00      0.00        23

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      4811

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([4788,   23]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ADASYN

In [17]:
try:
    from imblearn.over_sampling import ADASYN
    rebalance_train_test_logreg(X, y, ADASYN(), 'ADASYN',test_size)
except:
    print("Erro!")

-------------------------------ADASYN test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8565786738723759
 Precision Score: [0.99878286 0.02560455]
 Recall Score: [0.856934  0.7826087]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.78      0.92      0.82      0.68      4788
          1       0.03      0.78      0.86      0.05      0.82      0.67        23

avg / total       0.99      0.86      0.78      0.92      0.82      0.68      4811

 Sensitivity specificity support:
(array([0.856934 , 0.7826087]), array([0.7826087, 0.856934 ]), array([4788,   23]))
 Sensitivity score: 0.782608695652174
 Specificity score: 0.8569340016708438
 Geometric mean score: 0.8189285691118713


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BorderlineSMOTE

In [18]:
try:
    from imblearn.over_sampling import BorderlineSMOTE
    rebalance_train_test_logreg(X, y, BorderlineSMOTE(), 'BorderlineSMOTE',test_size)
except:
    print("Erro!")

-------------------------------BorderlineSMOTE test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9183122012055706
 Precision Score: [0.99773499 0.03282828]
 Recall Score: [0.92000835 0.56521739]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.92      0.57      0.96      0.72      0.54      4788
          1       0.03      0.57      0.92      0.06      0.72      0.50        23

avg / total       0.99      0.92      0.57      0.95      0.72      0.54      4811

 Sensitivity specificity support:
(array([0.92000835, 0.56521739]), array([0.56521739, 0.92000835]), array([4788,   23]))
 Sensitivity score: 0.5652173913043478
 Specificity score: 0.9200083542188805
 Geometric mean score: 0.7211135291684674


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# KMeansSMOTE

In [19]:
try:
    from imblearn.over_sampling import KMeansSMOTE
    rebalance_train_test_logreg(X, y, KMeansSMOTE(), 'KMeansSMOTE',test_size)
except:
    print("Erro!")

Erro!


# RandomOverSampler

In [20]:
try:
    from imblearn.over_sampling import RandomOverSampler
    rebalance_train_test_logreg(X, y, RandomOverSampler(), 'RandomOverSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomOverSampler test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8484722510912492
 Precision Score: [0.9987712  0.02425876]
 Recall Score: [0.84878864 0.7826087 ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.85      0.78      0.92      0.82      0.67      4788
          1       0.02      0.78      0.85      0.05      0.82      0.66        23

avg / total       0.99      0.85      0.78      0.91      0.82      0.67      4811

 Sensitivity specificity support:
(array([0.84878864, 0.7826087 ]), array([0.7826087 , 0.84878864]), array([4788,   23]))
 Sensitivity score: 0.782608695652174
 Specificity score: 0.8487886382623224
 Geometric mean score: 0.815027219836774


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTE

In [21]:
try:
    from imblearn.over_sampling import SMOTE
    rebalance_train_test_logreg(X, y, SMOTE(), 'SMOTE',test_size)
except:
    print("Erro!")

-------------------------------SMOTE test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8605279567657451
 Precision Score: [0.99878847 0.02631579]
 Recall Score: [0.86090226 0.7826087 ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.78      0.92      0.82      0.68      4788
          1       0.03      0.78      0.86      0.05      0.82      0.67        23

avg / total       0.99      0.86      0.78      0.92      0.82      0.68      4811

 Sensitivity specificity support:
(array([0.86090226, 0.7826087 ]), array([0.7826087 , 0.86090226]), array([4788,   23]))
 Sensitivity score: 0.782608695652174
 Specificity score: 0.8609022556390977
 Geometric mean score: 0.8208225090540151


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTENC

In [22]:
try:
    from imblearn.over_sampling import SMOTENC
    rebalance_train_test_logreg(X, y, SMOTENC(), 'SMOTENC',test_size)
except:
    print("Erro!")

Erro!


# SVMSMOTE

In [23]:
try:
    from imblearn.over_sampling import SVMSMOTE
    rebalance_train_test_logreg(X, y, SVMSMOTE(), 'SVMSMOTE',test_size)
except:
    print("Erro!")

-------------------------------SVMSMOTE test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9295364789025151
 Precision Score: [0.99731724 0.03254438]
 Recall Score: [0.93170426 0.47826087]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.93      0.48      0.96      0.67      0.47      4788
          1       0.03      0.48      0.93      0.06      0.67      0.43        23

avg / total       0.99      0.93      0.48      0.96      0.67      0.47      4811

 Sensitivity specificity support:
(array([0.93170426, 0.47826087]), array([0.47826087, 0.93170426]), array([4788,   23]))
 Sensitivity score: 0.4782608695652174
 Specificity score: 0.931704260651629
 Geometric mean score: 0.6675310403845398


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTEENN

In [24]:
try:
    from imblearn.combine import SMOTEENN
    rebalance_train_test_logreg(X, y, SMOTEENN(), 'SMOTEENN',test_size)
except:
    print("Erro!")

-------------------------------SMOTEENN test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8580336728330908
 Precision Score: [0.99854263 0.02449568]
 Recall Score: [0.85860485 0.73913043]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.74      0.92      0.80      0.64      4788
          1       0.02      0.74      0.86      0.05      0.80      0.63        23

avg / total       0.99      0.86      0.74      0.92      0.80      0.64      4811

 Sensitivity specificity support:
(array([0.85860485, 0.73913043]), array([0.73913043, 0.85860485]), array([4788,   23]))
 Sensitivity score: 0.7391304347826086
 Specificity score: 0.8586048454469507
 Geometric mean score: 0.7966310141600433


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTETomek

In [25]:
try:
    from imblearn.combine import SMOTETomek
    rebalance_train_test_logreg(X, y, SMOTETomek(), 'SMOTETomek',test_size)
except:
    print("Erro!")


-------------------------------SMOTETomek test size=0.3--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8613593847432967
 Precision Score: [0.99878964 0.02647059]
 Recall Score: [0.86173768 0.7826087 ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.78      0.93      0.82      0.68      4788
          1       0.03      0.78      0.86      0.05      0.82      0.67        23

avg / total       0.99      0.86      0.78      0.92      0.82      0.68      4811

 Sensitivity specificity support:
(array([0.86173768, 0.7826087 ]), array([0.7826087 , 0.86173768]), array([4788,   23]))
 Sensitivity score: 0.782608695652174
 Specificity score: 0.8617376775271512
 Geometric mean score: 0.8212206766782346


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BalancedBaggingClassifier

In [26]:
try:
    from imblearn.ensemble import BalancedBaggingClassifier
    rebalance_train_test_logreg(X, y, BalancedBaggingClassifier(), 'BalancedBaggingClassifier',test_size)
except:
    print("Erro!")

Erro!


# BalancedRandomForestClassifier

In [27]:
try:
    from imblearn.ensemble import BalancedRandomForestClassifier
    rebalance_train_test_logreg(X, y, BalancedRandomForestClassifier(), 'BalancedRandomForestClassifier',test_size)
except:
    print("Erro!")

Erro!


# EasyEnsemble

In [28]:
try:
    from imblearn.ensemble import EasyEnsembleClassifier
    rebalance_train_test_logreg(X, y, EasyEnsembleClassifier(), 'EasyEnsembleClassifier',test_size)
except:
    print("Erro!")

Erro!


# RUSBoostClassifier

In [29]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!


# RUSBoostClassifier

In [30]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!
