Lê os dados:

In [1]:
import pandas as pd
df = pd.read_csv("Base_Dissertacaov10.csv",sep=';',decimal=",",encoding = "latin")
# print(df.head())

In [2]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
#Cria os dados
y = df["AUTO"].to_numpy()
X = df.iloc[:,3:-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 12345)

#Padroniza os dados
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Random Over Sampler

In [3]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=12345)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score
logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')


 Accuracy Score: 0.9956348216512846
 Precision Score: [0.99563482 0.        ]
 Recall Score: [1. 0.]


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Over Sampler
Copiado de : https://audreymychan.com/unbalancedclasses.html

In [5]:
# Method to rebalance train data, model a logistic regression, and output charts for predictions on test data
# Inputs: X data, y data, rebalance algorithm (i.e. SMOTE()), rebalancing_title as a str (i.e. 'SMOTE')
from imblearn.metrics import classification_report_imbalanced, sensitivity_specificity_support,sensitivity_score,specificity_score,geometric_mean_score, make_index_balanced_accuracy
def rebalance_train_test_logreg(X, y, rebalance_alg, rebalancing_title, test_size=0.2):

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = 12345)

    scaler = preprocessing.StandardScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Rebalance train data
    rebalance = rebalance_alg
    X_reb, y_reb = rebalance.fit_sample(X_train, y_train)

    # Train a Logistic Regression model on resampled data
    logreg = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
    logreg.fit(X_reb, y_reb)

    # Generate predictions
    y_pred = logreg.predict(X_test)

    # Print out metrics
    print(f'-------------------------------{rebalancing_title} test size={test_size}--------------------------------------')
    print("----------   Standard Metrics   -------------------")
    print(f' Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f' Precision Score: {precision_score(y_test, y_pred, average = None)}')
    print(f' Recall Score: {recall_score(y_test, y_pred, average = None)}')
    print("----------   Imbalanced Metrics   -------------------")
    print(f' Classification report imbalanced: {classification_report_imbalanced(y_test, y_pred)}')
    print(f' Sensitivity specificity support:')
    print(sensitivity_specificity_support(y_test, y_pred))
    print(f' Sensitivity score: {sensitivity_score(y_test, y_pred)}')
    print(f' Specificity score: {specificity_score(y_test, y_pred)}')
    print(f' Geometric mean score: {geometric_mean_score(y_test, y_pred)}')

    return None


# ClusterCentroids

In [6]:
test_size=0.5
try:
    from imblearn.under_sampling import ClusterCentroids
    rebalance_train_test_logreg(X, y, ClusterCentroids(), 'ClusterCentroids',test_size)
except:
    print("Erro!")


-------------------------------ClusterCentroids test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.7944624594662011
 Precision Score: [0.99905467 0.01735488]
 Recall Score: [0.79431291 0.82857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.79      0.83      0.88      0.81      0.66      7983
          1       0.02      0.83      0.79      0.03      0.81      0.66        35

avg / total       0.99      0.79      0.83      0.88      0.81      0.66      8018

 Sensitivity specificity support:
(array([0.79431291, 0.82857143]), array([0.82857143, 0.79431291]), array([7983,   35]))
 Sensitivity score: 0.8285714285714286
 Specificity score: 0.7943129149442566
 Geometric mean score: 0.8112613553400029


# CondensedNearestNeighbour

In [7]:
try:
    from imblearn.under_sampling import CondensedNearestNeighbour
    rebalance_train_test_logreg(X, y, CondensedNearestNeighbour(), 'CondensedNearestNeighbour',test_size)
except:
    print("Erro!")


-------------------------------CondensedNearestNeighbour test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9930157146420554
 Precision Score: [0.99587139 0.08      ]
 Recall Score: [0.99711888 0.05714286]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.06      1.00      0.24      0.06      7983
          1       0.08      0.06      1.00      0.07      0.24      0.05        35

avg / total       0.99      0.99      0.06      0.99      0.24      0.06      8018

 Sensitivity specificity support:
(array([0.99711888, 0.05714286]), array([0.05714286, 0.99711888]), array([7983,   35]))
 Sensitivity score: 0.05714285714285714
 Specificity score: 0.9971188776149317
 Geometric mean score: 0.23870111348294143


# EditedNearestNeighbours

In [8]:
try:
    from imblearn.under_sampling import EditedNearestNeighbours
    rebalance_train_test_logreg(X, y, EditedNearestNeighbours(), 'EditedNearestNeighbours',test_size)
except:
    print("Erro!")

-------------------------------EditedNearestNeighbours test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.995260663507109
 Precision Score: [0.99563319 0.        ]
 Recall Score: [0.9996242 0.       ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      7983
          1       0.00      0.00      1.00      0.00      0.00      0.00        35

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      8018

 Sensitivity specificity support:
(array([0.9996242, 0.       ]), array([0.       , 0.9996242]), array([7983,   35]))
 Sensitivity score: 0.0
 Specificity score: 0.9996242014280345
 Geometric mean score: 0.0


# EditedNearestNeighbours

In [9]:
try:
    from imblearn.under_sampling import RepeatedEditedNearestNeighbours
    rebalance_train_test_logreg(X, y, RepeatedEditedNearestNeighbours(), 'RepeatedEditedNearestNeighbours',test_size)
except:
    print("Erro!")


-------------------------------RepeatedEditedNearestNeighbours test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.995260663507109
 Precision Score: [0.99612839 0.36363636]
 Recall Score: [0.99912314 0.11428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.11      1.00      0.34      0.12      7983
          1       0.36      0.11      1.00      0.17      0.34      0.10        35

avg / total       0.99      1.00      0.12      0.99      0.34      0.12      8018

 Sensitivity specificity support:
(array([0.99912314, 0.11428571]), array([0.11428571, 0.99912314]), array([7983,   35]))
 Sensitivity score: 0.11428571428571428
 Specificity score: 0.999123136665414
 Geometric mean score: 0.33791345243004184


# AllKNN

In [10]:
try:
    from imblearn.under_sampling import AllKNN
    rebalance_train_test_logreg(X, y, AllKNN(), 'AllKNN',test_size)
except:
    print("Erro!")

-------------------------------AllKNN test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9950112247443252
 Precision Score: [0.9956321 0.       ]
 Recall Score: [0.99937367 0.        ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      7983
          1       0.00      0.00      1.00      0.00      0.00      0.00        35

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      8018

 Sensitivity specificity support:
(array([0.99937367, 0.        ]), array([0.        , 0.99937367]), array([7983,   35]))
 Sensitivity score: 0.0
 Specificity score: 0.9993736690467243
 Geometric mean score: 0.0


# InstanceHardnessThreshold

In [11]:
try:
    from imblearn.under_sampling import InstanceHardnessThreshold
    rebalance_train_test_logreg(X, y, InstanceHardnessThreshold(), 'InstanceHardnessThreshold',test_size)
except:
    print("Erro!")


-------------------------------InstanceHardnessThreshold test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9890246944375156
 Precision Score: [0.99710364 0.15584416]
 Recall Score: [0.9918577  0.34285714]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.99      0.34      0.99      0.58      0.36      7983
          1       0.16      0.34      0.99      0.21      0.58      0.32        35

avg / total       0.99      0.99      0.35      0.99      0.58      0.36      8018

 Sensitivity specificity support:
(array([0.9918577 , 0.34285714]), array([0.34285714, 0.9918577 ]), array([7983,   35]))
 Sensitivity score: 0.34285714285714286
 Specificity score: 0.9918576976074157
 Geometric mean score: 0.5831513494132913


# NearMiss

In [12]:
try:
    from imblearn.under_sampling import NearMiss
    rebalance_train_test_logreg(X, y, NearMiss(), 'NearMiss',test_size)
except:
    print("Erro!")

-------------------------------NearMiss test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.05562484410077326
 Precision Score: [0.98352941 0.00368761]
 Recall Score: [0.05236127 0.8       ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.05      0.80      0.10      0.20      0.04      7983
          1       0.00      0.80      0.05      0.01      0.20      0.05        35

avg / total       0.98      0.06      0.80      0.10      0.20      0.04      8018

 Sensitivity specificity support:
(array([0.05236127, 0.8       ]), array([0.8       , 0.05236127]), array([7983,   35]))
 Sensitivity score: 0.8
 Specificity score: 0.05236126769384943
 Geometric mean score: 0.20466805846316016


# NeighbourhoodCleaningRule

In [13]:
try:
    from imblearn.under_sampling import NeighbourhoodCleaningRule
    rebalance_train_test_logreg(X, y, NeighbourhoodCleaningRule(), 'NeighbourhoodCleaningRule',test_size)
except:
    print("Erro!")

-------------------------------NeighbourhoodCleaningRule test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.995260663507109
 Precision Score: [0.99563319 0.        ]
 Recall Score: [0.9996242 0.       ]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      7983
          1       0.00      0.00      1.00      0.00      0.00      0.00        35

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      8018

 Sensitivity specificity support:
(array([0.9996242, 0.       ]), array([0.       , 0.9996242]), array([7983,   35]))
 Sensitivity score: 0.0
 Specificity score: 0.9996242014280345
 Geometric mean score: 0.0


# OneSidedSelection

In [14]:
try:
    from imblearn.under_sampling import OneSidedSelection
    rebalance_train_test_logreg(X, y, OneSidedSelection(), 'OneSidedSelection',test_size)
except:
    print("Erro!")

-------------------------------OneSidedSelection test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9956348216512846
 Precision Score: [0.99563482 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      7983
          1       0.00      0.00      1.00      0.00      0.00      0.00        35

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      8018

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([7983,   35]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RandomUnderSampler

In [15]:
try:
    from imblearn.under_sampling import RandomUnderSampler
    rebalance_train_test_logreg(X, y, RandomUnderSampler(), 'RandomUnderSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomUnderSampler test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8167872287353455
 Precision Score: [0.99953988 0.02136182]
 Recall Score: [0.81635976 0.91428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.82      0.91      0.90      0.86      0.74      7983
          1       0.02      0.91      0.82      0.04      0.86      0.75        35

avg / total       1.00      0.82      0.91      0.89      0.86      0.74      8018

 Sensitivity specificity support:
(array([0.81635976, 0.91428571]), array([0.91428571, 0.81635976]), array([7983,   35]))
 Sensitivity score: 0.9142857142857143
 Specificity score: 0.8163597644995616
 Geometric mean score: 0.8639363809908686


# TomekLinks

In [16]:
try:
    from imblearn.under_sampling import TomekLinks
    rebalance_train_test_logreg(X, y, TomekLinks(), 'TomekLinks',test_size)
except:
    print("Erro!")

-------------------------------TomekLinks test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9956348216512846
 Precision Score: [0.99563482 0.        ]
 Recall Score: [1. 0.]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.00      1.00      0.00      0.00      7983
          1       0.00      0.00      1.00      0.00      0.00      0.00        35

avg / total       0.99      1.00      0.00      0.99      0.00      0.00      8018

 Sensitivity specificity support:
(array([1., 0.]), array([0., 1.]), array([7983,   35]))
 Sensitivity score: 0.0
 Specificity score: 1.0
 Geometric mean score: 0.0


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# ADASYN

In [17]:
try:
    from imblearn.over_sampling import ADASYN
    rebalance_train_test_logreg(X, y, ADASYN(), 'ADASYN',test_size)
except:
    print("Erro!")

-------------------------------ADASYN test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8611873285108506
 Precision Score: [0.99869338 0.02300885]
 Recall Score: [0.86170613 0.74285714]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.74      0.93      0.80      0.65      7983
          1       0.02      0.74      0.86      0.04      0.80      0.63        35

avg / total       0.99      0.86      0.74      0.92      0.80      0.65      8018

 Sensitivity specificity support:
(array([0.86170613, 0.74285714]), array([0.74285714, 0.86170613]), array([7983,   35]))
 Sensitivity score: 0.7428571428571429
 Specificity score: 0.861706125516723
 Geometric mean score: 0.8000778402029713


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BorderlineSMOTE

In [18]:
try:
    from imblearn.over_sampling import BorderlineSMOTE
    rebalance_train_test_logreg(X, y, BorderlineSMOTE(), 'BorderlineSMOTE',test_size)
except:
    print("Erro!")

-------------------------------BorderlineSMOTE test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.946994262908456
 Precision Score: [0.99749868 0.03791469]
 Recall Score: [0.94914193 0.45714286]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.95      0.46      0.97      0.66      0.46      7983
          1       0.04      0.46      0.95      0.07      0.66      0.41        35

avg / total       0.99      0.95      0.46      0.97      0.66      0.46      8018

 Sensitivity specificity support:
(array([0.94914193, 0.45714286]), array([0.45714286, 0.94914193]), array([7983,   35]))
 Sensitivity score: 0.45714285714285713
 Specificity score: 0.9491419265940123
 Geometric mean score: 0.6587058920013261


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# KMeansSMOTE

In [19]:
try:
    from imblearn.over_sampling import KMeansSMOTE
    rebalance_train_test_logreg(X, y, KMeansSMOTE(), 'KMeansSMOTE',test_size)
except:
    print("Erro!")

Erro!


# RandomOverSampler

In [20]:
try:
    from imblearn.over_sampling import RandomOverSampler
    rebalance_train_test_logreg(X, y, RandomOverSampler(), 'RandomOverSampler',test_size)
except:
    print("Erro!")

-------------------------------RandomOverSampler test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8618109254178099
 Precision Score: [0.99869433 0.02311111]
 Recall Score: [0.86233246 0.74285714]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.86      0.74      0.93      0.80      0.65      7983
          1       0.02      0.74      0.86      0.04      0.80      0.63        35

avg / total       0.99      0.86      0.74      0.92      0.80      0.65      8018

 Sensitivity specificity support:
(array([0.86233246, 0.74285714]), array([0.74285714, 0.86233246]), array([7983,   35]))
 Sensitivity score: 0.7428571428571429
 Specificity score: 0.8623324564699988
 Geometric mean score: 0.8003685556081553


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTE

In [21]:
try:
    from imblearn.over_sampling import SMOTE
    rebalance_train_test_logreg(X, y, SMOTE(), 'SMOTE',test_size)
except:
    print("Erro!")

-------------------------------SMOTE test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8699176852082814
 Precision Score: [0.99856322 0.02362949]
 Recall Score: [0.87060003 0.71428571]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.71      0.93      0.79      0.63      7983
          1       0.02      0.71      0.87      0.05      0.79      0.61        35

avg / total       0.99      0.87      0.71      0.93      0.79      0.63      8018

 Sensitivity specificity support:
(array([0.87060003, 0.71428571]), array([0.71428571, 0.87060003]), array([7983,   35]))
 Sensitivity score: 0.7142857142857143
 Specificity score: 0.8706000250532381
 Geometric mean score: 0.788579203854827


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTENC

In [22]:
try:
    from imblearn.over_sampling import SMOTENC
    rebalance_train_test_logreg(X, y, SMOTENC(), 'SMOTENC',test_size)
except:
    print("Erro!")

Erro!


# SVMSMOTE

In [23]:
try:
    from imblearn.over_sampling import SVMSMOTE
    rebalance_train_test_logreg(X, y, SVMSMOTE(), 'SVMSMOTE',test_size)
except:
    print("Erro!")

-------------------------------SVMSMOTE test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.9598403591918184
 Precision Score: [0.99740293 0.04731861]
 Recall Score: [0.96216961 0.42857143]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.96      0.43      0.98      0.64      0.43      7983
          1       0.05      0.43      0.96      0.09      0.64      0.39        35

avg / total       0.99      0.96      0.43      0.98      0.64      0.43      8018

 Sensitivity specificity support:
(array([0.96216961, 0.42857143]), array([0.42857143, 0.96216961]), array([7983,   35]))
 Sensitivity score: 0.42857142857142855
 Specificity score: 0.9621696104221471
 Geometric mean score: 0.6421513874988004


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTEENN

In [24]:
try:
    from imblearn.combine import SMOTEENN
    rebalance_train_test_logreg(X, y, SMOTEENN(), 'SMOTEENN',test_size)
except:
    print("Erro!")

-------------------------------SMOTEENN test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.865552506859566
 Precision Score: [0.99869999 0.02374429]
 Recall Score: [0.86609044 0.74285714]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.74      0.93      0.80      0.65      7983
          1       0.02      0.74      0.87      0.05      0.80      0.64        35

avg / total       0.99      0.87      0.74      0.92      0.80      0.65      8018

 Sensitivity specificity support:
(array([0.86609044, 0.74285714]), array([0.74285714, 0.86609044]), array([7983,   35]))
 Sensitivity score: 0.7428571428571429
 Specificity score: 0.866090442189653
 Geometric mean score: 0.8021106353495664


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# SMOTETomek

In [25]:
try:
    from imblearn.combine import SMOTETomek
    rebalance_train_test_logreg(X, y, SMOTETomek(), 'SMOTETomek',test_size)
except:
    print("Erro!")


-------------------------------SMOTETomek test size=0.5--------------------------------------
----------   Standard Metrics   -------------------
 Accuracy Score: 0.8670491394362684
 Precision Score: [0.99870224 0.02400739]
 Recall Score: [0.86759364 0.74285714]
----------   Imbalanced Metrics   -------------------
 Classification report imbalanced:                    pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.87      0.74      0.93      0.80      0.65      7983
          1       0.02      0.74      0.87      0.05      0.80      0.64        35

avg / total       0.99      0.87      0.74      0.92      0.80      0.65      8018

 Sensitivity specificity support:
(array([0.86759364, 0.74285714]), array([0.74285714, 0.86759364]), array([7983,   35]))
 Sensitivity score: 0.7428571428571429
 Specificity score: 0.8675936364775148
 Geometric mean score: 0.8028064087653544


/Users/pedro/Library/Python/3.7/lib/python/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# BalancedBaggingClassifier

In [26]:
try:
    from imblearn.ensemble import BalancedBaggingClassifier
    rebalance_train_test_logreg(X, y, BalancedBaggingClassifier(), 'BalancedBaggingClassifier',test_size)
except:
    print("Erro!")

Erro!


# BalancedRandomForestClassifier

In [27]:
try:
    from imblearn.ensemble import BalancedRandomForestClassifier
    rebalance_train_test_logreg(X, y, BalancedRandomForestClassifier(), 'BalancedRandomForestClassifier',test_size)
except:
    print("Erro!")

Erro!


# EasyEnsemble

In [28]:
try:
    from imblearn.ensemble import EasyEnsembleClassifier
    rebalance_train_test_logreg(X, y, EasyEnsembleClassifier(), 'EasyEnsembleClassifier',test_size)
except:
    print("Erro!")

Erro!


# RUSBoostClassifier

In [29]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!


# RUSBoostClassifier

In [30]:
try:
    from imblearn.ensemble import RUSBoostClassifier
    rebalance_train_test_logreg(X, y, RUSBoostClassifier(), 'RUSBoostClassifier',test_size)
except:
    print("Erro!")


Erro!
